workflows:
  android-zip-build:
    name: Build Android APK from ZIP
    instance_type: mac_mini_m1
    scripts:
      - name: Extract ZIP files
        script: |
          unzip -o ShiftAir.zip
          # Sogeza mafile yote kutoka folda yoyote kwenda root
          find . -maxdepth 2 -name "gradlew" -execdir cp -r ./* $CM_BUILD_DIR/ \; || true
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/**/*.apk"
